# -*- coding: utf-8 -*-
"""Assign_houses.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10TLx5NISFySSRD5dNCdi1udl6a7htpUS
"""

from math import sqrt
import random
import numpy as np
import pandas as pd
import itertools
import csv

#importing the files

from google.colab import files
uploaded=files.upload()

f = open('rating.csv')
csv_f = csv.reader(f)
price=[]
location=[]
mode_of_sharing=[]
flat_type=[]

for column in csv_f:
  price.append(column[1])
  location.append(column[2])
  mode_of_sharing.append(column[3])
  flat_type.append(column[4])
  
print(price)
print(location)
print(mode_of_sharing)
print(flat_type)

price.remove('Price')
location.remove('Location')
mode_of_sharing.remove('Mode_of_Sharing')
flat_type.remove('Flat_type')

f = open('housedata.csv')
csv_f = csv.reader(f)
price_1=[]
location_1=[]
type=[]
size=[]

for column in csv_f:
  location_1.append(column[1])
  price_1.append(column[2])
  
  type.append(column[4])
  size.append(column[3])

print(price_1)
print(location_1)
print(type)
print(size)

price_1.remove('price')
location_1.remove('Location')
type.remove('type')
size.remove('size')

print(price_1)
print(location_1)
print(type)
print(size)

f = open('housing.csv')
csv_f = csv.reader(f)
price_2=[]
location_2=[]
type_2=[]
size_2=[]
desc_tennants=[]

for column in csv_f:
  price_2.append(column[1])
  type_2.append(column[2])
  desc_tennants.append(column[3])
  size_2.append(column[4])
  location_2.append(column[5])

print(price_2)
print(location_2)
print(type_2)
print(size_2)
print(desc_tennants)

price_2.remove('Description_Rent')
location_2.remove('Location')
type_2.remove('Description_Furnishing')
size_2.remove('Flat type(BHK)')
desc_tennants.remove('Description_Tenants')

print(price_2)
print(location_2)
print(type_2)
print(size_2)
print(desc_tennants)

#storing the user ratings in a list

user_rating=[]
for i in range(0,30):
  user_rating.append([price[i],location[i],mode_of_sharing[i],flat_type[i]])

print(user_rating)

#storing the user choices in a list
user_choice=[]
for i in range(0,30):
  user_choice.append([price_1[i],location_1[i],type[i],size[i]])

print(user_choice)

#storing the available choices in a list

available_choice=[]
for i in range(0,30):
  available_choice.append([price_2[i],location_2[i],type_2[i],size_2[i], desc_tennants[i]])

print(available_choice)

#storing the ratings of user and then finding recommended houses


u_ratings=user_rating[0]

most_imp=max(u_ratings)
idx=u_ratings.index(most_imp)
user_wants=user_choice[0]
recommended=[]

for i in range(0,30):
  
  available=available_choice[i]
  if (user_wants[idx]==available[idx]):
    recommended.append(available)

recommended

temp=u_ratings
temp[idx]='0'
print(temp)

second_imp=max(temp)
idx=temp.index(second_imp)
print(idx)
length= len(recommended)
print(length)

for i,j in range(0,length):
  
  recommend=recommended[j]
  if (user_wants[idx]!=recommend[idx]):
    recommended.remove(recommend)

print(recommended)

temp[idx]='0'
print(temp)

third_imp=max(temp)
idx=temp.index(third_imp)
print(idx)
length= len(recommended)
print(length)

for j in range(0,length):
  
  recommend=recommended[j]
  if (user_wants[idx]!=recommend[idx]):
    recommended.remove(recommend)

print(recommended)

